# 1. MySQL connection
# Local database config
spring.datasource.url=jdbc:mysql://localhost:3307/mak_it_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# 2. JPA / Hibernate
# Generic MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Server port
server.port=8080

# 4. JWT
security.jwt.secret=YjVhZjM4OWYxZjIxZDAxYzEwMTA2NDU2OGQ0YzQ2Mzk4OGIwM2Q0N2M5Y2E4MWQ0M2Q4N2Q2NzQ2YmQ0NQ==
security.jwt.expiration-ms=86400000